### ISSUE TITLE
Error installing via `pip`

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml-renderer#2]
I attempted to install this package into a fresh virtual environment using `pip`:

```shell
python -m venv .venv
source .venv/bin/activate
pip install linkml-renderer
```

This resulted in the following error:

```shell
Collecting importlib<2.0.0,>=1.0.4
  Using cached importlib-1.0.4.zip (7.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

For reference:

```
$ python --version
Python 3.9.13

$ pip --version
pip 22.0.4 from [...]/.venv/lib/python3.9/site-packages/pip (python 3.9)

$ pip list
Package    Version
---------- -------
pip        22.0.4
setuptools 58.1.0
```

**Comment by pkalita-lbl** [comment]
I think the root cause here is the [dependency](https://github.com/linkml/linkml-renderer/blob/d92fd7464562d0316f9b01e1cc56fc76af953087/pyproject.toml#L14) on the [importlib package](https://pypi.org/project/importlib/) which is some ancient compatibility-layer package.

**Comment by hrshdhgd** [comment]
This is what I did and it worked (not saying this is the solution and don't know why it worked).
```
python -m venv .venv
source .venv/bin/activate
pip install linkml
pip install linkml-renderer
```

The `pip install linkml` could be any pip package (I randomly chose linkml). The error does not occur .

**Comment by cmungall** [comment]
@hrshdhgd - can we remove importlib from the cookiecutter? https://github.com/hrshdhgd/sphintoxetry-cookiecutter/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml#L14

(and from this repo)

**Comment by hrshdhgd** [comment]
The sole purpose of `importlib` is [__version__](https://github.com/linkml/linkml-renderer/blob/d92fd7464562d0316f9b01e1cc56fc76af953087/src/linkml_renderer/__init__.py#L2)
